### ISSUE TITLE
AWS Worker nodes lack permissions to successfully run AWS EBS Driver

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1219]
**Description**

AWS EBS driver can't attach volumes.

The PVC's aren't being attached. Looking at logs it seems that the pods don't have enough credentials:

```console
$ kl -l app=ebs-csi-controller -c ebs-plugin
E1126 10:30:52.693448       1 driver.go:111] GRPC error: rpc error: code = Internal desc = NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: EC2MetadataError: failed to make EC2Metadata request
        status code: 404, request id:
```

Opening up the networkpolicy did not help.

**Impact**

The pods' don't get volumes attached and PVC stay in `Pending` state for a long time.

**Environment and steps to reproduce**

On an AWS setup, I have `enable_csi = true` in the `cluster` block. And following component config:

```hcl
component "aws-ebs-csi-driver" {
  enable_default_storage_class = true
}
```

**Expected behavior**

I expected the volumes to be attached successfully.

**Comment by surajssd** [comment]
I created a pod, which has labels that match the networkpolicy for EBS:

```
kubectl -n kube-system run -l app=ebs-csi-controller,app.kubernetes.io/instance=aws-ebs-csi-driver,app.kubernetes.io/name=aws-ebs-csi-driver  -it --rm debug-network-$RANDOM --image-pull-policy=Always --image=quay.io/surajd/fedora-networking --restart=Never bash
```

And inside I installed the aws cli:

```bash
dnf -y install unzip
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install
```

And after I run this command:

```log
[root@debug-network-3472 /]# aws --debug ec2 describe-snapshots --owner self
2020-11-26 12:27:04,572 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.4 Python/3.7.3 Linux/5.4.77-flatcar exe/x86_64.fedora.32
2020-11-26 12:27:04,573 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'ec2', 'describe-snapshots', '--owner', 'self']
2020-11-26 12:27:04,595 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.4/dist/awscli/data/cli.json
2020-11-26 12:27:04,604 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.1.4 Python/3.7.3 Linux/5.4.77-flatcar exe/x86_64.fedora.32
2020-11-26 12:27:04,604 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 'ec2', 'describe-snapshots', '--owner', 'self']
2020-11-26 12:27:04,607 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2020-11-26 12:27:04,627 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.4/dist/botocore/data/ec2/2016-11-15/service-2.json
2020-11-26 12:27:04,701 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-instance
2020-11-26 12:27:04,701 - MainThread - awscli.customizations.removals - DEBUG - Removing operation: import-volume
2020-11-26 12:27:04,714 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.4/dist/botocore/data/ec2/2016-11-15/waiters-2.json
2020-11-26 12:27:04,716 - MainThread - awscli.clidriver - DEBUG - OrderedDict([('filters', <awscli.arguments.ListArgument object at 0x7fe081cfeb00>), ('max-results', <awscli.arguments.CLIArgument object at 0x7fe081cfeb38>), ('next-token', <awscli.arguments.CLIArgument object at 0x7fe081cfeb70>), ('owner-ids', <awscli.arguments.ListArgument object at 0x7fe081cfebe0>), ('restorable-by-user-ids', <awscli.arguments.ListArgument object at 0x7fe081cfeba8>), ('snapshot-ids', <awscli.arguments.ListArgument object at 0x7fe081cfec18>), ('dry-run', <awscli.arguments.BooleanArgument object at 0x7fe081cfecf8>), ('no-dry-run', <awscli.arguments.BooleanArgument object at 0x7fe081cfecc0>)])
2020-11-26 12:27:04,731 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.4/dist/botocore/data/ec2/2016-11-15/paginators-1.json
2020-11-26 12:27:04,732 - MainThread - awscli.customizations.paginate - DEBUG - Modifying paging parameters for operation: DescribeSnapshots
2020-11-26 12:27:04,736 - MainThread - awscli.arguments - DEBUG - Unpacked value of ['self'] for parameter "owner_ids": ['self']
2020-11-26 12:27:04,738 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2020-11-26 12:27:04,739 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2020-11-26 12:27:05,742 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2020-11-26 12:27:05,744 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/placement/availability-zone/ HTTP/1.1" 200 13
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2020-11-26 12:27:05,745 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: custom-process
2020-11-26 12:27:05,746 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2020-11-26 12:27:05,746 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2020-11-26 12:27:05,746 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2020-11-26 12:27:05,746 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
2020-11-26 12:27:05,746 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role
2020-11-26 12:27:05,747 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2020-11-26 12:27:06,749 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2020-11-26 12:27:06,751 - MainThread - urllib3.connectionpool - DEBUG - http://169.254.169.254:80 "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 404 339
2020-11-26 12:27:06,752 - MainThread - botocore.utils - DEBUG - Metadata service returned non-200 response with status code of 404 for url: http://169.254.169.254/latest/meta-data/iam/security-credentials/, content body: b'<?xml version="1.0" encoding="iso-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n\t\t "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n <head>\n  <title>404 - Not Found</title>\n </head>\n <body>\n  <h1>404 - Not Found</h1>\n </body>\n</html>\n'
2020-11-26 12:27:06,753 - MainThread - botocore.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2020-11-26 12:27:06,754 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /usr/local/aws-cli/v2/2.1.4/dist/botocore/data/endpoints.json
2020-11-26 12:27:06,782 - MainThread - botocore.endpoint - DEBUG - Setting ec2 timeout as (60, 60)
2020-11-26 12:27:06,792 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=DescribeSnapshots) with params: {'url_path': '/', 'query_string': '', 'method': 'POST', 'headers': {'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': 'aws-cli/2.1.4 Python/3.7.3 Linux/5.4.77-flatcar exe/x86_64.fedora.32 command/ec2.describe-snapshots'}, 'body': {'Action': 'DescribeSnapshots', 'Version': '2016-11-15', 'Owner.1': 'self', 'MaxResults': 1000}, 'url': 'https://ec2.eu-central-1.amazonaws.com/', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x7fe08175a898>, 'has_streaming_input': False, 'auth_type': None}}
2020-11-26 12:27:06,793 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "awscli/clidriver.py", line 453, in main
  File "awscli/clidriver.py", line 582, in __call__
  File "awscli/clidriver.py", line 761, in __call__
  File "awscli/clidriver.py", line 891, in invoke
  File "awscli/clidriver.py", line 913, in _display_response
  File "awscli/formatter.py", line 82, in __call__
  File "botocore/paginate.py", line 449, in build_full_result
  File "botocore/paginate.py", line 255, in __iter__
  File "botocore/paginate.py", line 332, in _make_request
  File "botocore/client.py", line 249, in _api_call
  File "botocore/client.py", line 555, in _make_api_call
  File "botocore/client.py", line 574, in _make_request
  File "botocore/endpoint.py", line 102, in make_request
  File "botocore/endpoint.py", line 132, in _send_request
  File "botocore/endpoint.py", line 116, in create_request
  File "botocore/hooks.py", line 227, in emit
  File "botocore/hooks.py", line 210, in _emit
  File "botocore/signers.py", line 90, in handler
  File "botocore/signers.py", line 162, in sign
  File "botocore/auth.py", line 357, in add_auth
botocore.exceptions.NoCredentialsError: Unable to locate credentials

Unable to locate credentials. You can configure credentials by running "aws configure".
```

Notice that I can reach the metadata service, but I consistently get `404`s.

**Comment by surajssd** [comment]
I have a controller node `ip-10-0-11-61` and following EBS pods are running on the controller node:

```console
$ kgp -A -o wide | grep ebs | grep ip-10-0-11-61
kube-system         ebs-csi-controller-664ff5c9b7-cv92h                      4/4     Running             0          33m   10.2.108.4   ip-10-0-11-61   <none>           <none>
kube-system         ebs-csi-node-jvqs4                                       3/3     Running             0          33m   10.0.11.61   ip-10-0-11-61   <none>           <none>
```

Turns out only controller nodes has permission:

```console
$ k exec -it ebs-csi-node-jvqs4 bash
bash-4.2# curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
terraform-20201126115712776500000001
```

This is opposite of what we need. Like mentioned in #1199 controller nodes should not even have `ebs-csi-node` pod running and all workers should have IAM permissions.

**Comment by ipochi** [comment]
PR: #1271
