### ISSUE TITLE
TestPrometheusOperatorDeployment times out and produces the below error stack

### ISSUE THREAD

**Issue by ipochi** [kinvolk/lokomotive#326]
TestPrometheusOperatorDeployment has a timeout of 10 mins, once the timeout is triggered there should be graceful exit and Failed test rather the below stack error message.

```
satefulset: alertmanager-prometheus-operator-alertmanager, replicas: 0/1
    TestPrometheusOperatorDeployment/statefulset_alertmanager-prometheus-operator-alertmanager: util.go:86: statefulset: alertmanager-prometheus-operator-alertmanager, replicas: 0/1
    TestPrometheusOperatorDeployment/statefulset_prometheus-prometheus-operator-prometheus: util.go:86: statefulset: prometheus-prometheus-operator-prometheus, replicas: 0/1
coverage: [no statements]
panic: test timed out after 10m0s

goroutine 412 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1460 +0xdf
created by time.goFunc
	/usr/local/go/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0002c4d80, 0x13551b9, 0x20, 0x13d2eb0, 0x48ea26)
	/usr/local/go/src/testing/testing.go:1044 +0x37e
testing.runTests.func1(0xc0002c4c60)
	/usr/local/go/src/testing/testing.go:1285 +0x78
testing.tRunner(0xc0002c4c60, 0xc000187dd8)
	/usr/local/go/src/testing/testing.go:992 +0xdc
testing.runTests(0xc000296820, 0x1dd37e0, 0x1, 0x1, 0x0)
	/usr/local/go/src/testing/testing.go:1283 +0x2a7
testing.(*M).Run(0xc0002e6080, 0x0)
	/usr/local/go/src/testing/testing.go:1200 +0x15f
main.main()
	_testmain.go:86 +0x1c1

goroutine 19 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x1deac20)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/klog/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/klog/klog.go:411 +0xd6

goroutine 20 [chan receive, 9 minutes]:
testing.tRunner.func1(0xc0002c4d80)
	/usr/local/go/src/testing/testing.go:957 +0x238
testing.tRunner(0xc0002c4d80, 0x13d2eb0)
	/usr/local/go/src/testing/testing.go:996 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 24 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc0005ac000, 0xc00065bea0, 0xc0004a20c0, 0x0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:432 +0x10f
k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc0005ac000, 0xc0005abea0, 0x0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:320 +0x87
k8s.io/apimachinery/pkg/util/wait.Poll(0x12a05f200, 0x8bb2c97000, 0xc0005abea0, 0x12cf84493, 0x1dea7e0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:314 +0x4d
github.com/kinvolk/lokomotive/test/components/util.WaitForStatefulSet(0xc000319560, 0x1521c80, 0xc0002c6b00, 0x134116d, 0xa, 0x136470b, 0x2d, 0x1, 0x12a05f200, 0x8bb2c97000)
	/tmp/build/499b39e3/lokoctl/test/components/util/util.go:76 +0xee
github.com/kinvolk/lokomotive/test/components/prometheus-operator.TestPrometheusOperatorDeployment.func2(0xc000319560)
	/tmp/build/499b39e3/lokoctl/test/components/prometheus-operator/prometheus_operator_test.go:64 +0xd5
testing.tRunner(0xc000319560, 0xc00036c8a0)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 25 [select]:
k8s.io/apimachinery/pkg/util/wait.WaitFor(0xc000530000, 0xc000661ea0, 0xc00052e060, 0x0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:432 +0x10f
k8s.io/apimachinery/pkg/util/wait.pollInternal(0xc000530000, 0xc0005a7ea0, 0x0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:320 +0x87
k8s.io/apimachinery/pkg/util/wait.Poll(0x12a05f200, 0x8bb2c97000, 0xc0005a7ea0, 0x12cfb2e13, 0x1dea7e0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:314 +0x4d
github.com/kinvolk/lokomotive/test/components/util.WaitForStatefulSet(0xc000319680, 0x1521c80, 0xc0002c6b00, 0x134116d, 0xa, 0x135f127, 0x29, 0x1, 0x12a05f200, 0x8bb2c97000)
	/tmp/build/499b39e3/lokoctl/test/components/util/util.go:76 +0xee
github.com/kinvolk/lokomotive/test/components/prometheus-operator.TestPrometheusOperatorDeployment.func2(0xc000319680)
	/tmp/build/499b39e3/lokoctl/test/components/prometheus-operator/prometheus_operator_test.go:64 +0xd5
testing.tRunner(0xc000319680, 0xc00036c8d0)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357

goroutine 36 [IO wait]:
internal/poll.runtime_pollWait(0x7fa72e1045e8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000410518, 0x72, 0x5c00, 0x5c46, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000410500, 0xc0003ae000, 0x5c46, 0x5c46, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000410500, 0xc0003ae000, 0x5c46, 0x5c46, 0x203000, 0x660e60, 0xc00048e138)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000486000, 0xc0003ae000, 0x5c46, 0x5c46, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0007b04c0, 0xc0003ae000, 0x5c46, 0x5c46, 0x1a, 0x1eb7, 0xc0004499c8)
	/usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00048e258, 0x14cf440, 0xc0007b04c0, 0x40c0f5, 0x1201020, 0x12ed180)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00048e000, 0x14d0540, 0xc000486000, 0x5, 0xc000486000, 0x9)
	/usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00048e000, 0x0, 0x0, 0xc000449d38)
	/usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00048e000, 0xc0004f3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc0004ec240, 0xc0004d6118, 0x9, 0x9, 0xc000449d38, 0x13d4100, 0x830065)
	/usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x14cf2c0, 0xc0004ec240, 0xc0004d6118, 0x9, 0x9, 0x9, 0xc000118030, 0x0, 0x14cf560)
	/usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc0004d6118, 0x9, 0x9, 0x14cf2c0, 0xc0004ec240, 0x0, 0x0, 0xc000197bc0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/golang.org/x/net/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0004d60e0, 0xc000197bc0, 0x0, 0x0, 0x0)
	/tmp/build/499b39e3/lokoctl/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000449fa8, 0xc0000d0fb0, 0x713632)
	/tmp/build/499b39e3/lokoctl/vendor/golang.org/x/net/http2/transport.go:1746 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc00048c180)
	/tmp/build/499b39e3/lokoctl/vendor/golang.org/x/net/http2/transport.go:1674 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/tmp/build/499b39e3/lokoctl/vendor/golang.org/x/net/http2/transport.go:674 +0x64a

goroutine 75 [select]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc0004a2180, 0x12a05f200, 0x8bb2c97000, 0xc0004a2120)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:481 +0x16a
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:464 +0x8c

goroutine 62 [select]:
k8s.io/apimachinery/pkg/util/wait.poller.func1.1(0xc00052e120, 0x12a05f200, 0x8bb2c97000, 0xc00052e0c0)
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:481 +0x16a
created by k8s.io/apimachinery/pkg/util/wait.poller.func1
	/tmp/build/499b39e3/lokoctl/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:464 +0x8c
FAIL	github.com/kinvolk/lokomotive/test/components/prometheus-operator	600.014s
```

**Comment by surajssd** [comment]
WIll increasing timeout help here? Like to say 15m? WDYT?

**Comment by invidian** [comment]
This test is using now default timehow, which is below 10 minutes deadline. It also no longer times out or is flaky. Closing.
