### ISSUE TITLE
aws-ebs-csi-driver component can't connect to EC2 instance metadata

### ISSUE THREAD

**Issue by invidian** [kinvolk/lokomotive#864]
It currently crashes with the following error:
```
+ kubectl logs -f ebs-csi-controller-585d6d6f56-hgn5d -c ebs-plugin
I0826 15:01:28.649833       1 driver.go:62] Driver: ebs.csi.aws.com Version: v0.5.0
panic: EC2 instance metadata is not available

goroutine 1 [running]:
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.newControllerService(0xc000191380, 0xc00001e960, 0x0, 0x16)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/controller.go:76 +0x103
github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver.NewDriver(0xc000115f70, 0x3, 0x3, 0xc000062900, 0xd4d780, 0xc000191260)
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/pkg/driver/driver.go:82 +0x3d9
main.main()
        /go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/cmd/main.go:31 +0x117
```

My guess is that EC2 instance metadata blocking has been implemented after this component has been added + there is a bug in the controller, that it reports that it's ready, even though it's not, which tricks our CI that the component is healthy.

**Comment by invidian** [comment]
Reported upstream: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/548.
